<a href="https://colab.research.google.com/github/lawsonhp/Hello-World/blob/master/MatrixManipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf

### Start an Interactive **Session**

In [0]:
sess = tf.InteractiveSession()

### Define a 5x5 Identity matrix

In [0]:
I_matrix = tf.eye(5)

In [7]:
print(I_matrix.eval())

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### This will print a 5x5 Identity matrix

### Define a Variable initialized to a 10x10 identity matrix
