<a href="https://colab.research.google.com/github/lawsonhp/Hello-World/blob/master/MatrixManipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf

### Start an Interactive **Session**

In [0]:
sess = tf.InteractiveSession()

### Define a 5x5 Identity matrix

In [0]:
I_matrix = tf.eye(5)

In [7]:
print(I_matrix.eval())

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### This will print a 5x5 Identity matrix

### Define a Variable initialized to a 10x10 identity matrix


In [8]:
X = tf.Variable(tf.eye(10))

Instructions for updating:
Colocations handled automatically by placer.


In [0]:
X.initializer.run()   # Initialize the Variable


In [10]:
print(X.eval())

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


### Evaluate the Variable and print the result

### Create a random 5x10 matrix

In [0]:
A = tf.Variable(tf.random_normal([5,10]))

In [0]:
A.initializer.run()

### #Multiply two matrices

In [0]:
product = tf.matmul(A, X)

In [15]:
print(product.eval())

[[ 1.7512647  -1.2182918  -0.17035773  0.838333   -1.7375373  -1.4828935
   1.1581136  -0.48930478 -0.00506215  0.74057925]
 [ 0.49066308 -0.7859757  -0.43351674 -0.526031   -1.0281767  -2.2764091
   1.4140553  -0.5911982  -0.67090994 -1.22134   ]
 [ 0.20010194  1.6685005   3.5313535   0.83060664 -0.1094161   0.27250758
   0.6143731   0.8543508   0.06490684 -2.330997  ]
 [ 1.4783388  -0.9925362   0.23818631 -1.2482107   2.146607    1.0650427
  -0.1821583  -0.920144    0.71338433 -0.12016686]
 [ 0.6641133  -3.3529215   0.9956702  -1.0194037   0.70983106 -0.20398043
  -1.5404446  -1.0595045  -1.203644    2.75627   ]]


### create a random matrix of 1s and 0s, size 5x10



In [0]:
b = tf.Variable(tf.random_uniform([5,10], 0, 2, dtype= tf.int32))

In [0]:
b.initializer.run()

In [18]:
print(b.eval())

[[0 1 0 0 0 1 1 0 0 1]
 [1 1 0 0 0 0 1 0 1 0]
 [0 1 0 1 0 1 1 1 1 1]
 [1 1 1 1 1 0 0 0 0 0]
 [1 1 0 0 1 1 1 1 1 1]]
